### PR TITLE
type hints

### PR DESCRIPTION
**Pull request by Anton-4**
Added:
- type hints
- nox for checking of type hints by travis

Updated:
- travis to automatically run nox

WIP because I still need to automatically strip the type hints to support python3.5 and below

### CODE REVIEW

**Comment by Anton-4** [comment]
@PaulSchweizer can you review when you have the time?

**Comment by Anton-4** [comment]
By the way, can you give me the ability to assign reviewers, assign people to issues...?

**Comment by PaulSchweizer** [comment]
This is really cool! Thanks again for the hard work @Anton-4 
I'm learning new stuff from you here, this is much appreciated!

**Comment by Anton-4** [comment]
You're very welcome :). Can you add a new release for the current master?

**Pull request merged**
